name: NightfallDebtSystem
version: '${project.version}'
main: org.kennji.nightfallDebtSystem.NightfallDebtSystem
api-version: '1.21'
authors: [ _kennji ]
depend: [CoinsEngine]
softdepend:
  - PlaceholderAPI

libraries:
  - 'com.zaxxer:HikariCP:5.0.1'

commands:
  debt:
    description: Main command for Nightfall Debt System
    aliases: [nfsdebt]
    usage: /<command> <subcommand>

